#! /bin/sh
# $Id: radiolist,v 1.13 2010/01/13 10:20:03 tom Exp $

. ./setup-vars
. ./setup-tempfile

output=$($DIALOG --backtitle "Step 1" \
	--title "SELECT NDK VERSION TO DOWNLOAD..." --clear "$@" \
	--stdout \
        --radiolist "" 10 61 5 \
        "r19c" "" on \
	"r18b" "" off )

echo $output

case "$output" in
	"r19c") echo "wybrano 19";
	wget https://dl.google.com/android/repository/android-ndk-r19c-linux-x86_64.zip;;
	"r18b") echo "wybrano 18";
	wget https://dl.google.com/android/repository/android-ndk-r18b-linux-x86_64.zip

esac

